name: Laravel Sail PHPUnit

on:
  push:
  pull_request:

jobs:
  test:
    name: Run all tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug
        run: |
          # Show UID
          echo "UID: $UID"
          # Show GID
          echo "GID: $GID"
          # Show current user
          echo "Current user: $(whoami)"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: json, curl, mbstring, zip, pcntl, exif, gd, pdo_mysql, bcmath, redis, memcached, xdebug, tokenizer, xml

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Copy .env.example file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Start Laravel Sail
        run: |
          ./vendor/bin/sail up -d

      - name: Run PHPUnit tests
        run: ./vendor/bin/sail artisan test

      - name: Stop Laravel Sail
        run: ./vendor/bin/sail down
